### ISSUE TITLE
When support for .net core?

### ISSUE THREAD

**Issue by ZeeLyn** [fsprojects/FSharp.Data.TypeProviders#16]
When support for .net core?

**Comment by enricosada** [comment]
~~@ww198643 Type provider require .net standard 2.0.~~

~~See [visualfsharp roadmap](https://github.com/Microsoft/visualfsharp/issues/2400) for more info~~

Edited, will not work in 2.0 either, see https://github.com/fsprojects/FSharp.Data.TypeProviders/issues/16#issuecomment-311347828 below

**Comment by ed-ilyin** [comment]
I'm trying to use this lib in netstandard2.0 preview1 project, but getting error at compile time
```
FSC : error FS3031: The type provider 'C:\Users\edil\.nuget\packages\fsharp.data.typeproviders\5.0.0.2\lib\net40\FSharp.Data.TypeProviders.dll' reported an error: Assembly attribute 'TypeProviderAssemblyAttribute' refers to a designer assembly 'FSharp.Data.TypeProviders' which cannot be loaded or doesn't exist. Could not load file or assembly 'FSharp.Data.TypeProviders, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified. [C:\Users\edil\git\MyProject.fsproj]
```

**Comment by enricosada** [comment]
Type providers doesnt work in 2.0 either.
VF# team updated the roadmap and excluded type providers for 2.0, see https://github.com/Microsoft/visualfsharp/issues/3069 for more info

**Comment by larjo** [comment]
I understand that I cant use type providers when targeting netstandard2.0.

But shouldn't they work when I target net461?
```

> dotnet --version
1.0.4

> gc .\src\library\library.fsproj | select -index 2
<TargetFramework>net461</TargetFramework>

> dotnet add .\src\library\library.fsproj package FSharp.Data.TypeProviders
> dotnet restore
> dotnet build
...
 error FS3031: The type provider 'C:\Users\lbr606\.nuget\packages\fsharp.data.typeproviders\5.0.0.2\lib\net40\FSharp.Data.TypeProviders.dll' reported an error: Assembly attribute 'TypeProviderAssemblyAttribute' refers to a designer assembly 'FSharp.Data.TypeProviders' which cannot be loaded or doesn't exist. Could not load file or assembly 'FSharp.Data.TypeProviders, Culture=neutral, PublicKeyToken=null'.
```

**Comment by dsyme** [comment]
@larjo Please add a bug at http://github.com/Microsoft/visualfsharp. This is likely to be a limitation of using the F# compiler when executing on .NET Core.

**Comment by dsyme** [comment]
@larjo The error is different when using .NET SDK 2.0 preview2, see https://github.com/Microsoft/visualfsharp/issues/3303

**Comment by dsyme** [comment]
@larjo We have looked into this.  You can use type providers with the new project file format when targeting net461, you just need to either  compile using "msbuild", or apply the second workaround listed in https://github.com/Microsoft/visualfsharp/issues/3303

**Comment by gfritz** [comment]
I tried the workaround documented in this https://github.com/Microsoft/visualfsharp/issues/3303#issuecomment-312966306 with WsdlService. The approach in that comment still fails for me, however the error is different from the other errors in that issue:
```
FSC : error FS2024: Static linking may not be used on an assembly referencing mscorlib (e.g. a .NET Framework assembly) when generating an assembly that references System.Runtime (e.g. a .NET Core or Portable assembly). [C:\git\tp-tests\wsdlserviceapp\wsdlserviceapp.fsproj]
```

![image](https://user-images.githubusercontent.com/2267030/34543922-5c00b062-f0b1-11e7-98b2-0189ef6d2cd0.png)

Is FS2024 happening primarily because the Type Providers in FSharp.Data.TypeProviders are not "cross targeting" like in the linked comment? I could not find a way to determine if they were or were not. I have a test repo https://github.com/gfritz/wsdlserviceapp and a README with steps and screenshots.

**Comment by daz10000** [comment]
Is there any update on this?  - we have been using FSharp.Data extensively with dotnet core (mainly the type providers like CSV and XML provider) and then using the magic workaround https://github.com/Microsoft/visualfsharp/issues/3303 to keep the tooling happy.   It all works, but only downside is lots of warnings every time you run the executable.      Would be great to get a clean FSharp.Data build on dotnet core ,

Darren

```:\src\DemGslc\src\DemGslc\DemGslc.fsproj : warning NU1701: Package 'FSharp.Data 2.4.5' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.```

**Comment by dsyme** [comment]
> Is there any update on this? - we have been using FSharp.Data extensively with dotnet core (mainly the type providers like CSV and XML provider) and then using the magic workaround Microsoft/visualfsharp#3303 to keep the tooling happy. It all works, but only downside is lots of warnings every time you run the executable. Would be great to get a clean FSharp.Data build on dotnet core ,


Do you mean http://github.com/fsharp/FSharp.Data, rather than this set of (old) type providers?

**Comment by daz10000** [comment]
Ooops - yes ;)  didnt notice I was in the wrong project.

**Comment by dsyme** [comment]
Note this is a very old collection of type providers that are Windows-specific and .NET Framework-specific. For up-to-date type providers see https://fsharp.org/guides/data-access/

For WSDL see https://github.com/fsprojects/FSharp.Data.WsdlProvider for a more recent provider, also https://github.com/fsprojects/SwaggerProvider
