### ISSUE TITLE
WsdlService not working with VS2017 15.7.0

### ISSUE THREAD

**Issue by avalente** [fsprojects/FSharp.Data.TypeProviders#30]
### Description

After upgrading to Visual Studio 15.7.0 the type provider doesn't compile.

### Repro steps

I can reproduce it with a minimal example:

1. Create a file named `example.fs` with the following lines
```fsharp
open FSharp.Data.TypeProviders

type Wsdl1 = WsdlService<"http://api.microsofttranslator.com/V2/Soap.svc">
```
2. compile with the following command line

```cmd
    "C:\Program Files (x86)\Microsoft SDKs\F#\10.1\Framework\v4.0\fsc.exe" --times --nocopyfsharpcore -r:"fsharp.data.typeproviders\5.0.0.3-beta\lib\net40\FSharp.Data.TypeProviders.dll" -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.2\System.ServiceModel.dll" example.fs 
```
  `fsharp.data.typeproviders` is the folder copied from my `.nuget`

### Expected behavior

The code should compile without problems, I just tried it on a Visual Studio version 15.6.7

### Actual behavior

The compilation fails with the following error:

`error FS0193: Il file 'C:\Users\MyUser\ExampleFolder\tmpBC2F.dll' non è stato trovato.`

which is "File not found" in italian. Here is the complete output of the given command line:

```cmd
Microsoft (R) F# Compiler version 10.1.0 for F# 4.1
Copyright (c) Microsoft Corporation. All Rights Reserved.

warning FS0075: The command-line option 'times' is for test purposes only
TIME:  0.3 Delta:  0.1 Mem:  67 G0:   1 G1:  1 G2:  1 [Import mscorlib and FSharp.Core.dll]
TIME:  0.3 Delta:  0.0 Mem:  70 G0:   0 G1:  0 G2:  0 [Parse inputs]
TIME:  0.3 Delta:  0.0 Mem:  78 G0:   0 G1:  0 G2:  0 [Import non-system references]
TIME:  0.6 Delta:  0.3 Mem:  97 G0:   1 G1:  0 G2:  0 [Typecheck]
TIME:  0.6 Delta:  0.0 Mem:  97 G0:   0 G1:  0 G2:  0 [Typechecked]
TIME:  0.6 Delta:  0.0 Mem:  97 G0:   0 G1:  0 G2:  0 [Write Interface File]
TIME:  0.6 Delta:  0.0 Mem:  97 G0:   0 G1:  0 G2:  0 [Write XML document signatures]
TIME:  0.6 Delta:  0.0 Mem:  97 G0:   0 G1:  0 G2:  0 [Write XML docs]
TIME:  0.6 Delta:  0.0 Mem:  97 G0:   0 G1:  0 G2:  0 [Write HTML docs]
TIME:  0.7 Delta:  0.1 Mem: 102 G0:   0 G1:  0 G2:  0 [Encode Interface Data]
TIME:  0.7 Delta:  0.0 Mem: 102 G0:   0 G1:  0 G2:  0 [Optimizations]
TIME:  0.7 Delta:  0.0 Mem: 102 G0:   0 G1:  0 G2:  0 [Ending Optimizations]
TIME:  0.7 Delta:  0.0 Mem: 102 G0:   0 G1:  0 G2:  0 [Encoding OptData]

example.fs(3,75): warning FS0988: Main module of program is empty: nothing will happen when it is run
TIME:  0.7 Delta:  0.0 Mem: 103 G0:   0 G1:  0 G2:  0 [TAST -> IL]
TIME:  0.7 Delta:  0.0 Mem: 103 G0:   0 G1:  0 G2:  0 [Find assembly references]
TIME:  0.8 Delta:  0.0 Mem: 105 G0:   0 G1:  0 G2:  0 [Static link]
ilwrite: TIME      0.000 (total)        0.781 (delta) - Write Started

error FS0193: Il file 'C:\Users\MyUser\ExampleFolder\tmpBC2F.dll' non è stato trovato.
STATS: #ByteArrayFile = 5, #MemoryMappedFileOpen = 27, #MemoryMappedFileClosed = 0, #RawMemoryFile = 0, #WeakByteArrayFile = 0
```

The temporary `.dll` file doesn't exist indeed, it looks like it gets created somewhere else, but some other function looks for it in the source's folder.

I tried with both the current production version on `nuget.org`, `5.0.0.2` and the beta `5.0.0.3-beta` with no luck.
Of course the same issue arises when compiling a complete solution from VS.

### Known workarounds

None I am aware of.

### Related information 

* Windows 10 Enterprise (10.0.15063)
* Visual Studio 15.7.0 and related tools
* .NET Framework 4.6.2 and 4.7

**Comment by avalente** [comment]
Some more details:

1. The same code shown above works in interactive (`fsi`)
2. The issue persists with the just released version of Visual Studio, `15.7.1`

**Comment by toburger** [comment]
I found a temporary Workaround to get msbuild and Visual Studio to work:

Set the `FscToolPath` environment variable to a known working `fsc.exe` folder path.

E.g. in PowerShell you could set it with

```powershell
$env:FscToolPath = "C:\SourceCode\fsharp\visualfsharp\Release\net40\bin"
```

Running msbuild in the same PowerShell session works for me.

> By the way: it seems that the latest version of fsc.exe compiled from the https://github.com/microsoft/visualfsharp repo doesn't have the error.

If you want to get Visual Studio to work you have to set the `FscToolPath` environment variable on a system level or launch it from the "patched" PowerShell instance.

**Comment by jamessdixon** [comment]
I am running into the same issue and I cannot update the FacToolPath.  Is there a fix that happen inside the package?

**Comment by dsyme** [comment]
Note this is a very old collection of type providers that are Windows-specific and .NET Framework-specific. For up-to-date type providers see https://fsharp.org/guides/data-access/

See https://github.com/fsprojects/FSharp.Data.WsdlProvider for a more recent provider, also https://github.com/fsprojects/SwaggerProvider
